plugins {
    id 'ultramemorycore.loader-conventions'
    id 'fabric-loom'
}

dependencies {
    minecraft group: 'com.mojang', name: 'minecraft', version: minecraft_version

    implementation group: 'net.fabricmc', name: 'fabric-loader', version: loader_version

    implementation project(':Common')
}

loom {
    runs {
        client {
            client()
            runDir('run')
        }
        server {
            server()
            runDir('run')
        }
    }
}
