plugins {
    id 'net.fabricmc.fabric-loom'
    id 'ultramemorycore.loader-conventions'
}

evaluationDependsOn(':Common')

repositories {
    maven { url 'https://maven.fabricmc.net/' }
    maven { url 'https://maven.terraformersmc.com/releases/' }
    mavenCentral()
}

dependencies {
    // 1. Minecraft
    minecraft "com.mojang:minecraft:26.2"

    // 2. Subproject Common
    implementation project(':Common')
}

// 3. Inject mod dependencies trực tiếp vào Configuration Object của Loom
configurations.named('modImplementation').configure {
    dependencies.add(project.dependencies.create("net.fabricmc:fabric-loader:${project.loader_version}"))
    dependencies.add(project.dependencies.create("net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"))
    dependencies.add(project.dependencies.create("com.terraformersmc:modmenu:${project.modmenu_version}"))
}

loom {
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('run')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('run')
        }
    }
}

compileJava {
    source(project(':Common').sourceSets.main.allJava)
}

processResources {
    from(project(':Common').sourceSets.main.resources)
}
