plugins {
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
    id 'ultramemorycore.loader-conventions'
}

repositories {
    maven { url 'https://maven.fabricmc.net/' }
    maven { url 'https://maven.terraformersmc.com/releases/' }
    maven { url 'https://maven.shedaniel.me/' }
    mavenCentral()
}

dependencies {
    minecraft group: 'com.mojang', name: 'minecraft', version: minecraft_version

    implementation group: 'net.fabricmc', name: 'fabric-loader', version: loader_version

    modImplementation group: 'net.fabricmc.fabric-api', name: 'fabric-api', version: fabric_version
    modImplementation group: 'me.shedaniel.cloth', name: 'cloth-config-fabric', version: cloth_config_version
    modImplementation group: 'com.terraformersmc', name: 'modmenu', version: modmenu_version

    implementation 'com.google.code.gson:gson:2.13.1'
    implementation 'it.unimi.dsi:fastutil:8.5.18'

    implementation project(':Common')
}

loom {
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('run')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('run')
        }
    }
}
