plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
}

pluginManager.withPlugin('net.fabricmc.fabric-loom') {
    dependencies {
        mappings loom.officialMojangMappings()
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
