plugins {
    // 1. Khai báo Fabric Loom ở Root và set 'apply false' 
    // Cách này truyền Plugin Classpath xuống cho subproject :Fabric
    id 'net.fabricmc.fabric-loom'
}

allprojects {
    repositories {
        mavenCentral()
        maven { url 'https://maven.fabricmc.net/' }
        maven { url 'https://maven.terraformersmc.com/releases/' }
        maven { url 'https://maven.shedaniel.me/' }
    }
}
