plugins {
    id 'java-library'
    id 'net.fabricmc.fabric-loom'
}

repositories {
    maven { url 'https://maven.fabricmc.net/' }
    maven { url 'https://maven.terraformersmc.com/releases/' }
    mavenCentral()
}

dependencies {
    minecraft group: 'com.mojang', name: 'minecraft', version: minecraft_version

    compileOnly "net.fabricmc:fabric-loader:${loader_version}"
    compileOnly "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation 'com.google.code.gson:gson:2.13.1'
    implementation 'it.unimi.dsi:fastutil:8.5.18'

    compileOnly group: 'com.terraformersmc', name: 'modmenu', version: modmenu_version
    runtimeOnly group: 'com.terraformersmc', name: 'modmenu', version: modmenu_version

}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}
