name: Sync UltraMemoryCore only

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: port-26.2
          fetch-depth: 0

      - name: Remove old Java sources
        run: |
          rm -rf Common/src/main/java
          rm -rf Fabric/src/main/java

      - name: Recreate folders
        run: |
          mkdir -p Common/src/main/java/com
          mkdir -p Fabric/src/main/java/com

      - name: Copy ultramemorycore package to Common
        run: |
          cp -r src/main/java/com/ultramemorycore \
                Common/src/main/java/com/

      - name: Copy ultramemorycore package to Fabric
        run: |
          cp -r src/main/java/com/ultramemorycore \
                Fabric/src/main/java/com/

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add Common/src/main/java Fabric/src/main/java

          git commit -m "Sync ultramemorycore package" || echo "No changes"

          git push origin port-26.2
